# Generated by Django 3.1.5 on 2021-01-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuillPost',
            new_name='EditMain',
        ),
    ]
