# Generated by Django 3.1.5 on 2021-01-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210127_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('text', models.CharField(max_length=1000)),
                ('second_title', models.CharField(max_length=100)),
                ('datalatitude', models.CharField(max_length=10)),
                ('datalongitude', models.CharField(max_length=10)),
            ],
        ),
    ]
