# Generated by Django 3.1.5 on 2021-01-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mainpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainPage',
        ),
        migrations.AddField(
            model_name='editmain',
            name='datalatitude',
            field=models.CharField(default='55.76', max_length=10),
        ),
        migrations.AddField(
            model_name='editmain',
            name='datalongitude',
            field=models.CharField(default='37.64', max_length=10),
        ),
        migrations.AddField(
            model_name='editmain',
            name='first_title',
            field=models.CharField(default='Первый заголовок', max_length=100),
        ),
        migrations.AddField(
            model_name='editmain',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='editmain',
            name='second_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='editmain',
            name='text',
            field=models.CharField(default='Второй заголовок', max_length=1000),
        ),
    ]
