# Generated by Django 3.1.5 on 2021-01-27 13:42

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210127_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editmain',
            name='content',
        ),
        migrations.AlterField(
            model_name='editmain',
            name='first_title',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='editmain',
            name='second_title',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='editmain',
            name='text',
            field=django_quill.fields.QuillField(),
        ),
    ]
