# Generated by Django 3.1.5 on 2021-01-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210127_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageForMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(upload_to='mediafiles')),
            ],
        ),
        migrations.RemoveField(
            model_name='editmain',
            name='image',
        ),
        migrations.AlterField(
            model_name='editmain',
            name='first_title',
            field=models.CharField(default='Первый заголовок', max_length=100),
        ),
        migrations.AlterField(
            model_name='editmain',
            name='second_title',
            field=models.CharField(default='Второй заголовок', max_length=100),
        ),
    ]
