# Generated by Django 3.1.5 on 2021-01-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210127_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editmain',
            name='text',
            field=models.CharField(default='Текст', max_length=5000),
        ),
        migrations.AlterField(
            model_name='imageformain',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
