# Generated by Django 3.1.5 on 2021-01-28 16:14

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210128_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editmain',
            name='text',
            field=django_quill.fields.QuillField(),
        ),
    ]
