# Generated by Django 3.1.5 on 2021-01-28 16:15

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210128_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editmain',
            name='text',
            field=django_quill.fields.QuillField(default='Test2'),
        ),
    ]
