# Generated by Django 3.1.5 on 2021-01-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210128_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editmain',
            name='text',
            field=models.CharField(default='Текст', max_length=5000),
        ),
    ]
