# Generated by Django 3.1.5 on 2021-01-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210128_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Продукт test', max_length=100)),
                ('first_head', models.CharField(default='Заголовок 1', max_length=100)),
                ('first_text', models.CharField(default='Текст первого заголовка', max_length=1000)),
                ('second_head', models.CharField(default='Заголовок 2', max_length=100)),
                ('second_text', models.CharField(default='Текст второго заголовка', max_length=1000)),
                ('third_head', models.CharField(default='Заголовок 3', max_length=100)),
                ('third_text', models.CharField(default='Текст третьего заголовка', max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
