# Generated by Django 3.1.5 on 2021-01-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210130_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='first_text',
            new_name='first_text_1',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='second_text',
            new_name='second_text_1',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='third_text',
            new_name='third_text_1',
        ),
        migrations.AddField(
            model_name='products',
            name='first_text_2',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='products',
            name='first_text_3',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='products',
            name='product_name',
            field=models.CharField(default='Название продукта', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='second_text_2',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='products',
            name='second_text_3',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='products',
            name='third_text_2',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='products',
            name='third_text_3',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
