# Generated by Django 3.1.5 on 2021-01-30 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210130_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Текст', max_length=5000)),
                ('editmain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.editmain')),
            ],
        ),
    ]
