# Generated by Django 3.1.5 on 2021-01-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_extra_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editmain',
            name='text',
        ),
    ]
