# Generated by Django 3.1.5 on 2021-01-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_editmain_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_text',
            name='text',
            field=models.CharField(blank=True, default='Текст', max_length=5000),
        ),
    ]
