# Generated by Django 3.1.5 on 2021-01-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210130_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editmain',
            name='first_title',
        ),
        migrations.RemoveField(
            model_name='editmain',
            name='second_title',
        ),
        migrations.AddField(
            model_name='editmain',
            name='first_head',
            field=models.CharField(blank=True, default='Первый заголовок', max_length=100),
        ),
        migrations.AddField(
            model_name='editmain',
            name='second_head',
            field=models.CharField(blank=True, default='Второй заголовок', max_length=100),
        ),
        migrations.AddField(
            model_name='editmain',
            name='title',
            field=models.CharField(default='Главная', max_length=100),
        ),
        migrations.AddField(
            model_name='editmain',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='editmain',
            name='datalatitude',
            field=models.CharField(blank=True, default='55.76', max_length=10),
        ),
        migrations.AlterField(
            model_name='editmain',
            name='datalongitude',
            field=models.CharField(blank=True, default='37.64', max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='products'),
        ),
    ]
