# Generated by Django 3.1.5 on 2021-01-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210130_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='editmain',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='editmain',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='editmain',
            name='url',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='url',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
