# Generated by Django 3.1.5 on 2021-01-30 18:31

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210130_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageformain',
            name='image',
            field=models.ImageField(upload_to='', validators=[main.models.ImageForMain.validate_image]),
        ),
    ]
