# Generated by Django 3.1.5 on 2021-01-31 10:52

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210130_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageformain',
            name='image',
            field=models.ImageField(upload_to='', validators=[main.models.ImageForMain.validate_image, main.models.ImageForMain.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='products', validators=[main.models.Products.validate_image, main.models.Products.validate_file_extension]),
        ),
    ]
