# Generated by Django 3.1.5 on 2021-02-01 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210131_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='first_text_1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='first_text_2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='first_text_3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='second_text_1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='second_text_2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='second_text_3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='third_text_1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='third_text_2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='third_text_3',
        ),
        migrations.AlterField(
            model_name='products',
            name='first_head',
            field=models.CharField(blank=True, default='Заголовок 1', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Extra_Text_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products', to_field='first_head')),
            ],
        ),
    ]
