# Generated by Django 3.1.5 on 2021-02-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210201_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='first_head',
            field=models.CharField(blank=True, default='Заголовок 1', max_length=100, null=True, unique=True),
        ),
    ]
