# Generated by Django 3.1.5 on 2021-02-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210201_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extra_text_product',
            old_name='model',
            new_name='modelss',
        ),
    ]
