# Generated by Django 3.1.5 on 2021-02-01 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210201_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra_text_product',
            name='modelss',
        ),
        migrations.AddField(
            model_name='extra_text_product',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='extra_text_product',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.products'),
        ),
        migrations.AlterField(
            model_name='extra_text_product',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='products',
            name='first_head',
            field=models.CharField(blank=True, default='Заголовок 1', max_length=100),
        ),
    ]
