# Generated by Django 3.1.5 on 2021-02-01 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210201_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_text_product',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='extra_text_product',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.products'),
        ),
        migrations.AlterField(
            model_name='extra_text_product',
            name='text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
