# Generated by Django 3.1.5 on 2021-02-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210201_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_text_product',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
