# Generated by Django 3.1.5 on 2021-02-01 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210201_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_text_product',
            name='number',
            field=models.IntegerField(verbose_name=1),
        ),
        migrations.AlterField(
            model_name='extra_text_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products'),
        ),
    ]
