# Generated by Django 3.1.5 on 2021-02-01 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210201_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra_text_product',
            name='number',
        ),
    ]
