# Generated by Django 3.1.5 on 2021-02-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_extra_text_product_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_text_product',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
