# Generated by Django 3.1.5 on 2021-02-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20210201_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_text_product',
            name='nubmer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
